### ISSUE TITLE
Auto-deploy does not work

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/api-guidelines#120]
https://github.com/rust-lang-nursery/api-guidelines/pull/119#issuecomment-327471694

**Comment by KodrAus** [comment]
Hmm, looks like we might not have had any automatic deploys since moving the repo to the nursery? The build is complaining about the [script not being runnable](https://travis-ci.org/rust-lang-nursery/api-guidelines/builds/260720652#L639). I've just tried updating the file permissions in our index to see if that fixes it.

Just waiting on the build.

**Comment by KodrAus** [comment]
I'll just leave this open until we confirm everything is actually working.

**Comment by KodrAus** [comment]
@dtolnay [We might need to update the token we're using to push the contents](https://travis-ci.org/rust-lang-nursery/api-guidelines/builds/272698654#L642-L646)

**Comment by dtolnay** [comment]
I generated a new token and it seems to have published. Thanks for looking into this!
