### ISSUE TITLE
Discourage awkward reexports in favor of pub(restricted).

### ISSUE THREAD

**Issue by dragostis** [rust-lang-nursery/api-guidelines#59]
Instead of having awkward structures like:

```
my_mod_private/
  stuff/
other_mods_see_private_stuff/
```

and in `lib.rs`:

```rust
mod my_mod {
    // reexport what needs to be public from my_mod_private
}
```

we should make use of [pub(restricted)](https://github.com/rust-lang/rfcs/blob/master/text/1422-pub-restricted.md) (stabilized in 1.18).

**Comment by brson** [comment]
Seems like we need a concrete place where we've done this, and have a concrete pattern to suggest.

**Comment by dtolnay** [comment]
Thanks! I added a note about `pub(restricted)` in 2fb61613fb572f36b03444420deb9fcc5dab799a. For the purpose of the API guidelines this is only about removing things from the public API. I don't want to go into much more detail about advanced use of `pub(restricted)` because none of that affects the crate's API.
